spring.application.name=HotelBookingAndManagement

#DB Configuration
spring.datasource.url=enter url
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.context-path=/api/v1

jwt.secretKey=enter your secret key

frontend.url=http://localhost:8080
stripe.secret.key=enter your stripe key
stripe.webhook.secret=enter your key